### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by ellisgl** [Ayesh/Composer-Min-Autoload#1]
Would be interesting to see benchmarks to see if this help speed things up a tiny itsy-bitsy amount.

**Comment by Ayesh** [comment]
I don't think there will be any meaningful difference. My main use case was to reduce the git-diff noise. However, I suppose a tiny improvement of having to include one fewer file should be measurable over a few hundred thousand iterations. 

I will put together a rudimentary benchmark to see how many precious microseconds this would save :)
